MultiTaskTest.Visualization/Models/ErrorViewModel.cs
namespace MultiTaskTest.Visualization.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MultiTaskTest.Visualization/Models/ThreadMeasuresViewModel.cs
using System.Collections.Generic;

namespace MultiTaskTest.Visualization.Models
{
    public class ThreadMeasuresViewModel
    {
        public bool ShowThreadRace { get; set; }

        public IList<ThreadMetricViewModel> ThreadMetricViewModels { get; set; }

        public Dictionary<string, int> ComputationStatistic { get; set; }

        public long ElapsedTime { get; set; }

        public int ThreadsCount { get; set; }

        public ThreadMeasuresViewModel()
        {
            ThreadMetricViewModels = new List<ThreadMetricViewModel>();
        }
    }
}

MultiTaskTest.Visualization/Models/ThreadMetricViewModel.cs
using System.Collections.Generic;
using MultiTaskTest.Common.Statistic;

namespace MultiTaskTest.Visualization.Models
{
    public class ThreadMetricViewModel
    {
        public int ThreadId { get; set; }

        public string ThreadName { get; set; }

        public bool IsThreadFromPool { get; set; }

        public IList<TimeStamp> TimeBetweenIterations { get; set; }
    }
}

MultiTaskTest.Visualization/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using MultiTaskTest.Common;
using MultiTaskTest.Common.Statistic;

namespace MultiTaskTest.Visualization.Controllers
{
    [Produces("application/json")]
    [Route("api/app")]
    public class ApplicationController : Controller
    {
        private readonly ApplicationMap _applicationMap = new ApplicationMap(Constants.WebApplicationType);

        [HttpPost("run")]
        public IActionResult Run(ApplicationSettings settings)
        {
            ThreadsMeasures threadsMeasures = _applicationMap.Applications[settings.ApplicationName].Main(settings);

            return Json(threadsMeasures);
        }
    }
}

MultiTaskTest.Visualization/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MultiTaskTest.Common;
using MultiTaskTest.Common.Statistic;
using MultiTaskTest.Visualization.Builders;
using MultiTaskTest.Visualization.Models;

namespace MultiTaskTest.Visualization.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationMap _applicationMap = new ApplicationMap(Constants.WebApplicationType);

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Run(ApplicationSettings settings)
        {
            ThreadsMeasures threadsMeasures = _applicationMap.Applications[settings.ApplicationName].Main(settings);

            ThreadMeasuresViewModel threadMeasuresViewModel = ThreadMeasuresViewModelBuilder
                .CreateFrom(threadsMeasures)
                .WithShowThreadRace(settings.ShowThreadRace)
                .WithThreadMetrics()
                .Model();

            return PartialView(threadMeasuresViewModel);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MultiTaskTest.Visualization/Controllers/LogsController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Constants = MultiTaskTest.Common.Constants;

namespace MultiTaskTest.Visualization.Controllers
{
    public class LogsController : Controller
    {
        public IActionResult Index()
        {
            var directory = new DirectoryInfo(Constants.ExcelLogDirectory);

            IEnumerable<string> fileNames = directory.Exists
                ? directory.GetFiles().Select(x => x.Name)
                : Enumerable.Empty<string>();
            
            return View(fileNames);
        }

        public IActionResult Download(string fileName)
        {
            string filePath = Path.Combine(Constants.ExcelLogDirectory, fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Text.Xml, fileName);
        }

        [HttpPost]
        public IActionResult Clear()
        {
            var directory = new DirectoryInfo(Constants.ExcelLogDirectory);

            foreach (var fileInfo in directory.GetFiles())
            {
                fileInfo.Delete();
            }

            return new EmptyResult();
        }
    }
}

MultiTaskTest.Visualization/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<h2>This is a test application for comparing different approaches for Multitasking in .Net</h2>

<p>Following approaches implemented in this project:</p>
<ol>
    <li>Linq.ForAll</li>
    <li>Parallel.For</li>
    <li>Parallel.ForEach</li>
    <li>Parallel.Invoke</li>
    <li>Task.Run</li>
    <li>Task.Factory.StartNew</li>
    <li>ThreadPool.QueueUserWorkItem</li>
    <li>Thread.Start</li>
</ol>

<span>
    You can run each method as a standalone console application or run it through ASP.NET Core application. <br/>
    Also, you'll be able to see a thread race animation
</span>

MultiTaskTest.Visualization/Views/Home/Index.cshtml
@using MultiTaskTest.Common
@model ApplicationSettings
@{
    ViewData["Title"] = "Multitask test";
}

<h3>Pool size: @ThreadHelper.ThreadPoolSize</h3>
<h3>CPU count(Pool minimum): @ThreadHelper.MinimumThreadPoolSize</h3>
<div class="common-settings-container clearfix">
    <form id="commonSettings">
        <div class="col-md-12">
            <div class="form-group col-md-2">
                <label asp-for="IterationsCount">Iterations</label>
                <input asp-for="IterationsCount" min="0" type="number" value="100" class="form-control" placeholder="Iterations">
            </div>
            <div class="form-group col-md-2">
                <label asp-for="PowerValue">Power</label>
                <input asp-for="PowerValue" min="0" type="number" value="138000" class="form-control" placeholder="Power">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group col-md-2">
                <label asp-for="ScaleTicksValue">Speed scale</label>
                <input asp-for="ScaleTicksValue" min="1" type="number" value="1000" class="form-control" placeholder="Scale">
            </div>
            <div class="form-group col-md-2">
                <label asp-for="ThreadPoolMinimum">Pool minimum</label>
                <input asp-for="ThreadPoolMinimum" min="0" type="number" class="form-control" placeholder="Minimum">
            </div>
        </div>
        <div class="form-group col-md-12">
            <label asp-for="ShowThreadRace">Show thread race</label>
            <input asp-for="ShowThreadRace" type="checkbox" checked="checked">
        </div>
    </form>
    <button
            id="action-button"
            type="button"
            class="btn btn-primary btn-lg run-button"
            data-button-runapplication
            data-url="@Url.Action("Run", "Home")"
    >
        <i class="glyphicon glyphicon-play-circle"></i>
    </button>
</div>

<div class="clearfix">
    <ul class="nav nav-tabs tabs">
        <li class="active"><a data-tab="Linq.ForAll" href="#linq-forall">Linq.ForAll</a></li>
        <li><a data-tab="Parallel.For" href="#parallel-for">Parallel.For</a></li>
        <li><a data-tab="Parallel.ForEach" href="#parallel-foreach">Parallel.ForEach</a></li>
        <li><a data-tab="Parallel.Invoke" href="#parallel-invoke">Parallel.Invoke</a></li>
        <li><a data-tab="Task.Run" href="#task-run">Task.Run</a></li>
        <li><a data-tab="Task.Factory.StartNew" href="#task-factory">Task.Factory.StartNew</a></li>
        <li><a data-tab="ThreadPool.QueueUserWorkItem" href="#threadpool">ThreadPool.QueueUserWorkItem</a></li>
        <li><a data-tab="Thread.Start" href="#thread-start">Thread.Start</a></li>
    </ul>
    <div class="col-md-12" data-tab-content="Linq.ForAll" data-tab-content-active="true">
        <h2 id="linq-forall">Linq.ForAll</h2>
        <form data-from-settings-extended="Linq.ForAll">
            <input asp-for="ApplicationName" value="LinqForAll" type="hidden"/>
            <div class="form-group col-md-2">
                <label asp-for="MaxDegreeOfParallelism">Max degree</label>
                <input asp-for="MaxDegreeOfParallelism" min="0" type="number" class="form-control" placeholder="Degree">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Linq.ForAll"></div>
        <div class="loader hidden" data-amimation-loader="Linq.ForAll">
            <img class="loader-image" src="~/images/loader.gif"/>
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="Parallel.For" data-tab-content-active="false">
        <h2 id="parallel-for">Parallel.For</h2>
        <form data-from-settings-extended="Parallel.For">
            <input asp-for="ApplicationName" value="ParallelFor" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="MaxDegreeOfParallelism">Max degree</label>
                <input asp-for="MaxDegreeOfParallelism" min="0" type="number" class="form-control" placeholder="Degree">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Parallel.For"></div>
        <div class="loader hidden" data-amimation-loader="Parallel.For">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="Parallel.ForEach" data-tab-content-active="false">
        <h2 id="parallel-foreach">Parallel.ForEach</h2>
        <form data-from-settings-extended="Parallel.ForEach">
            <input asp-for="ApplicationName" value="ParallelForEach" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="MaxDegreeOfParallelism">Max degree</label>
                <input asp-for="MaxDegreeOfParallelism" min="0" type="number" class="form-control" placeholder="Degree">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Parallel.ForEach"></div>
        <div class="loader hidden" data-amimation-loader="Parallel.ForEach">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="Parallel.Invoke" data-tab-content-active="false">
        <h2 id="parallel-invoke">Parallel.Invoke</h2>
        <form data-from-settings-extended="Parallel.Invoke">
            <input asp-for="ApplicationName" value="ParallelInvoke" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="ActionsCount">Actions count</label>
                <input asp-for="ActionsCount" min="0" type="number" value="4" class="form-control" placeholder="Actions">
            </div>
            <div class="form-group col-md-2">
                <label asp-for="MaxDegreeOfParallelism">Max degree</label>
                <input asp-for="MaxDegreeOfParallelism" min="0" type="number" class="form-control" placeholder="Degree">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Parallel.Invoke"></div>
        <div class="loader hidden" data-amimation-loader="Parallel.Invoke">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="Task.Run" data-tab-content-active="false">
        <h2 id="task-run">Task.Run</h2>
        <form data-from-settings-extended="Task.Run">
            <input asp-for="ApplicationName" value="Tasks" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="ActionsCount">Actions count</label>
                <input asp-for="ActionsCount" min="0" type="number" value="4" class="form-control" placeholder="Actions">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Task.Run"></div>
        <div class="loader hidden" data-amimation-loader="Task.Run">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="Task.Factory.StartNew" data-tab-content-active="false">
        <h2 id="task-factory">Task.Factory.StartNew</h2>
        <form data-from-settings-extended="Task.Factory.StartNew">
            <input asp-for="ApplicationName" value="TaskFactory" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="ActionsCount">Actions count</label>
                <input asp-for="ActionsCount" min="0" type="number" value="4" class="form-control" placeholder="Actions">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Task.Factory.StartNew"></div>
        <div class="loader hidden" data-amimation-loader="Task.Factory.StartNew">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="ThreadPool.QueueUserWorkItem" data-tab-content-active="false">
        <h2 id="threadpool">ThreadPool.QueueUserWorkItem</h2>
        <form data-from-settings-extended="ThreadPool.QueueUserWorkItem">
            <input asp-for="ApplicationName" value="ThreadPool" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="ActionsCount">Actions count</label>
                <input asp-for="ActionsCount" min="0" type="number" value="4" class="form-control" placeholder="Actions">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="ThreadPool.QueueUserWorkItem"></div>
        <div class="loader hidden" data-amimation-loader="ThreadPool.QueueUserWorkItem">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>

    <div class="col-md-12 hidden" data-tab-content="Thread.Start" data-tab-content-active="false">
        <h2 id="thread-start">Thread.Start</h2>
        <form data-from-settings-extended="Thread.Start">
            <input asp-for="ApplicationName" value="Threads" type="hidden" />
            <div class="form-group col-md-2">
                <label asp-for="ActionsCount">Actions count</label>
                <input asp-for="ActionsCount" min="0" type="number" value="4" class="form-control" placeholder="Actions">
            </div>
            <div class="form-group col-md-2">
                <label asp-for="ThreadPriority">Thread priority</label>
                <input asp-for="ThreadPriority" min="0" type="number" value="2" class="form-control" placeholder="Priority">
            </div>
        </form>
        <div class="col-md-12" data-tab-animation="Thread.Start"></div>
        <div class="loader hidden" data-amimation-loader="Thread.Start">
            <img class="loader-image" src="~/images/loader.gif" />
        </div>
    </div>
</div>

MultiTaskTest.Visualization/Views/Home/Run.cshtml
@using MultiTaskTest.Common.Statistic
@model ThreadMeasuresViewModel
@{
    var carNumber = 0;
    var threadNumber = 0;
    var carsCount = 8;
    var threadTimelineScale = 85;
}

<div class="col-md-12">
    <h3>Timing: @Model.ElapsedTime ms</h3>
    <h4>Threads count: @Model.ThreadsCount</h4>
    @foreach (var computationStatistic in Model.ComputationStatistic)
    {
        <div>
            @{
                string threadType = Model.ThreadMetricViewModels.First(x => x.ThreadName == computationStatistic.Key).IsThreadFromPool
                    ? "from pool"
                    : "new";
            }
            @computationStatistic.Key (@threadType) calculated @computationStatistic.Value times.
        </div>
    }
</div>
@if (Model.ShowThreadRace)
{
    <div class="col-md-12">
        <img class="car" src="~/images/car_0.png" /> - Action <br />
        <img class="road" src="~/images/road.png" /> - Thread
    </div>

    <div class="animation-container" data-iterations-max="@Model.ThreadMetricViewModels.Select(x => x.TimeBetweenIterations.Count).Max()">
        @foreach (var threadMetric in Model.ThreadMetricViewModels)
        {
            <div class="thread-name">#@threadMetric.ThreadId @(threadMetric.ThreadName.Contains("Main") ? "(M)" : string.Empty)</div>
            <img data-start
                style="
                    position: absolute;
                    margin-top: @(threadNumber * 27)px;"
                 class="finish" src="~/images/start.jpg" />
            <div class="full-calculation-path" data-thread-name="@threadMetric.ThreadName">

                @foreach (TimeStamp iterationTime in threadMetric.TimeBetweenIterations)
                {
                    <div class="iteration"
                         data-iteration-time="@iterationTime.IterationTimeStamp"
                         data-iteration-thread="@threadMetric.ThreadName"
                         data-iteration-action="@(iterationTime.ActionId)">
                    </div>
                }

                <div data-action-active data-actionid="@threadMetric.TimeBetweenIterations[0].ActionId">
                    <img class="finish display-none" data-thread-completed="@threadMetric.ThreadName" src="~/images/finish.jpg" />
                </div>
            </div>
            {
                threadNumber++;
            }
        }

    </div>
    <div class="col-md-12">
        @foreach (var actions in Model.ThreadMetricViewModels.Select(x => x.TimeBetweenIterations))
        {
            foreach (var action in actions.GroupBy(x => x.ActionId))
            {
                <img data-action-pool data-actionid="@action.Key" class="car" src="~/images/car_@(carNumber++ % carsCount).png" />
            }
        }
    </div>
    <div data-thread-timing class="col-md-12 thread-timing-graph">
        <h1>Thread timeline</h1>
        <div class="thread-timing-container">
            @foreach (var threadMetric in Model.ThreadMetricViewModels)
            {
                <div class="thread-timing" 
                     style="
                        width: @(threadMetric.TimeBetweenIterations.Sum(x => x.IterationTimeStamp) / threadTimelineScale)px; 
                        margin-left: @(threadMetric.TimeBetweenIterations[0].IterationTimeStamp / threadTimelineScale)px;">
                    #@threadMetric.ThreadId @(threadMetric.ThreadName.Contains("Main") ? "(M)" : string.Empty)
                </div>
            }
        </div>
    </div>
}

MultiTaskTest.Visualization/Views/Logs/Index.cshtml
@using MultiTaskTest.Common
@model IEnumerable<string>
@{
    ViewData["Title"] = "Multitask test";
}

<div class="col-xs-12">
    
    <div data-logs-container>
        @foreach (var file in Model)
        {
            <h3>
                <a asp-action="Download" asp-route-fileName="@file">@file</a>
            </h3>
        }
    </div>

    <h3 data-logs-empty class="@(Model.Any() ? "display-none" : "")">Logs not exist</h3>
    
    @if (Model.Any())
    {
        <button class="btn btn-primary btn-lg" data-button-clearlogs data-url="@Url.Action("Clear", "Logs")">Clear logs</button>
    }
</div>

MultiTaskTest.Visualization/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Multitask Test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Logs" asp-action="Index">Logs</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
<div class="container">
    @RenderBody()
</div>
<footer>
    <p>Operation system: @Environment.OSVersion.ToString()</p>
    <p>Version: @Configuration.GetSection("Application")["Version"]</p>
</footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>